name: YouTube

on:
  workflow_dispatch:

jobs:
  build-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências e Tor
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
            -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt-get update && sudo apt-get install -y jq tor curl

      - name: Configurar Tor para saída nos EUA
        run: |
          echo "ExitNodes {us}" | sudo tee -a /etc/tor/torrc
          echo "StrictNodes 1"   | sudo tee -a /etc/tor/torrc
          sudo service tor restart
          sleep 10
          echo "IP de saída via Tor (deve ser US):"
          curl --socks5-hostname 127.0.0.1:9050 https://ifconfig.me || true

      - name: Criar arquivo de cookies
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Gerar playlist.m3u com tratamento de erros e proxies de fallback BR
        run: |
          # Não abortar no primeiro erro
          set +e

          echo "#EXTM3U" > playlist.m3u
          echo "## Playlist atualizada em: $(date)" >> playlist.m3u

          # proxies selecionados (high anonymity / socks4 sempre que possível)
          FALLBACK_PROXIES=(
            "socks4://186.251.253.53:31337"  # 947ms, High Anonymous
            "socks4://190.109.72.10:33633"   # 797ms, High Anonymous
            "socks4://45.191.13.6:4153"      # 958ms, High Anonymous
          )

          # lista de canais (JSON limpo, sem colchetes markdown)
          CHANNELS_JSON='[
            {
              "category": "Noticias",
              "name": "CNN Brasil",
              "logo": "https://yt3.googleusercontent.com/ytc/AIdro_lmJE_9aX-lvy2eliMO5ejbko3mQVM6Ecf79AR8pQFMcV8=s250-c-k-c0x00ffffff-no-rj",
              "live_url": "https://www.youtube.com/CNNbrasil/live"
            }
          ]'

          echo "$CHANNELS_JSON" \
            | jq -c '. | sort_by(.category, .name) | .[]' \
            | while read -r ch; do
              NAME=$(jq -r .name     <<<"$ch")
              CAT=$(jq -r .category <<<"$ch")
              LOGO=$(jq -r .logo     <<<"$ch")
              URL=$(jq -r .live_url  <<<"$ch")

              echo "=== Verificando: $NAME → $URL ==="

              M3U=""

              # 1) Rotaciona circuito Tor e tenta via Tor (SOCKS5)
              sudo killall -HUP tor && sleep 3
              echo "Tentando via Tor (socks5://127.0.0.1:9050)..."
              URL_M3U8=$(timeout 30 yt-dlp --cookies cookies.txt \
                           --proxy "socks5://127.0.0.1:9050" \
                           -f "best[height<=720]" -g "$URL" 2>/dev/null)
              if [ $? -eq 0 ] && [[ "$URL_M3U8" == *".m3u8"* ]]; then
                M3U="$URL_M3U8"
                echo "Sucesso via Tor"
              else
                echo "Falha via Tor"
              fi

              # 2) Se falhar, tenta proxies de fallback BR
              if [ -z "$M3U" ]; then
                for P in "${FALLBACK_PROXIES[@]}"; do
                  echo "Tentando proxy $P..."
                  URL_M3U8=$(timeout 30 yt-dlp --cookies cookies.txt \
                               --proxy "$P" \
                               -f "best[height<=720]" -g "$URL" 2>/dev/null)
                  if [ $? -eq 0 ] && [[ "$URL_M3U8" == *".m3u8"* ]]; then
                    M3U="$URL_M3U8"
                    echo "Sucesso com proxy $P"
                    break
                  else
                    echo "Falha com proxy $P"
                  fi
                done
              fi

              # 3) Adiciona à playlist se obteve URL válida
              if [ -n "$M3U" ]; then
                echo "" >> playlist.m3u
                echo "#EXTINF:-1 tvg-logo=\"$LOGO\" group-title=\"$CAT\",$NAME" >> playlist.m3u
                echo "$M3U" >> playlist.m3u
                echo "$NAME adicionado à playlist."
              else
                echo "Falha geral: $NAME offline ou bloqueado em todas as rotas."
              fi
            done

          echo "=== Verificação concluída ==="

      - name: Fazer commit
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add playlist.m3u
          if [ $(wc -l < playlist.m3u) -gt 2 ]; then
            git commit -m "Atualiza playlist de lives com fallback proxies BR"
            git push
            echo "Playlist atualizada."
          else
            echo "Nenhuma live ou todas falhas. Sem commit."
          fi
