name: YouTube

on:
  workflow_dispatch:

jobs:
  build-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências e Tor
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt-get update && sudo apt-get install -y jq tor curl

      - name: Configurar Tor para saída no Brasil
        run: |
          echo "ExitNodes {br}" | sudo tee -a /etc/tor/torrc
          echo "StrictNodes 1"   | sudo tee -a /etc/tor/torrc
          sudo service tor restart
          sleep 10

          echo "Verificando IP de saída via Tor:"
          curl --socks5-hostname 127.0.0.1:9050 https://ifconfig.me || true

      - name: Criar arquivo de cookies
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Gerar playlist.m3u com Tor
        run: |
          echo "#EXTM3U" > playlist.m3u
          echo "## Playlist atualizada em: $(date)" >> playlist.m3u

          CHANNELS_JSON='[
            {
              "category":"Noticias",
              "name":"CNN Brasil",
              "logo":"https://yt3.googleusercontent.com/ytc/AIdro_lmJE_9aX-lvy2eliMO5ejbko3mQVM6Ecf79AR8pQFMcV8=s250-c-k-c0x00ffffff-no-rj",
              "live_url":"https://www.youtube.com/CNNbrasil/live"
            }
          ]'

          echo "$CHANNELS_JSON" \
            | jq -c '. | sort_by(.category, .name) | .[]' \
            | while read -r ch; do
              NAME=$(jq -r .name     <<<"$ch")
              CAT=$(jq -r .category <<<"$ch")
              LOGO=$(jq -r .logo     <<<"$ch")
              URL=$(jq -r .live_url  <<<"$ch")

              echo "Verificando: $NAME → $URL"

              # Rotaciona circuito Tor
              sudo killall -HUP tor
              sleep 3

              # Tenta via Tor (resolvendo host via Tor)
              M3U=$(timeout 20 yt-dlp --cookies cookies.txt \
                       --proxy socks5h://127.0.0.1:9050 \
                       -f "best[height<=720]" --get-url "$URL" 2>/dev/null \
                     | grep -m1 m3u8 || true)

              if [ -n "$M3U" ]; then
                echo "" >> playlist.m3u
                echo "#EXTINF:-1 tvg-logo=\"$LOGO\" group-title=\"$CAT\",$NAME" >> playlist.m3u
                echo "$M3U" >> playlist.m3u
                echo "  Sucesso: $NAME adicionado."
              else
                echo "  Falha: $NAME offline ou bloqueado via Tor"
              fi
            done

          echo "Verificação concluída."

      - name: Fazer commit
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add playlist.m3u
          if [ $(wc -l < playlist.m3u) -gt 2 ]; then
            git commit -m "Atualiza playlist de lives via Tor"
            git push
            echo "Playlist atualizada."
          else
            echo "Nenhuma live. Sem commit."
          fi
